services:
  - type: web
    name: assistencia-juridica-frontend
    plan: free
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
 
    envVars:
      - key: NODE_VERSION
        value: 20
 
      - key: NEXT_PUBLIC_API_URL
        sync: false
 
      - key: NEXT_PUBLIC_WHATSAPP_NUMBER
        sync: false
 
      - key: NEXT_PUBLIC_COMPANY_EMAIL
        sync: false
 
  - type: web
    name: assistencia-juridica-backend
    plan: free
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma migrate deploy && npm run prisma:seed && npm run start
    healthCheckPath: /api/health
 
    envVars:
      - key: NODE_VERSION
        value: 20
 
      - key: NODE_ENV
        value: production
 
      - key: DATABASE_URL
        sync: false
 
      - key: JWT_SECRET
        generateValue: true
 
      - key: JWT_EXPIRES_IN
        value: 8h
 
      - key: FRONTEND_URL
        sync: false
 
      - key: MAX_FILE_SIZE_MB
        value: 10
 
      - key: UPLOAD_PROVIDER
        value: local
 
      - key: UPLOAD_DIR
        value: uploads
 
      - key: ADMIN_NAME
        sync: false
 
      - key: ADMIN_EMAIL
        sync: false
 
      - key: ADMIN_PASSWORD
        sync: false